"""Exact model catalog from tagger/utils.py, including v2.0 and main variants."""

MODELS = {
    "cl_tagger_1_01": {
        "kind": "cl",
        "repo_id": "cella110n/cl_tagger",
        "revision": "main",
        "model_path": "cl_tagger_1_01/model.onnx",
        "tags_path": "cl_tagger_1_01/tag_mapping.json",
    },
    "wd-eva02-large-tagger-v3": {
        "kind": "wd",
        "repo_id": "SmilingWolf/wd-eva02-large-tagger-v3",
        "revision": "main",
        "model_path": "model.onnx",
        "tags_path": "selected_tags.csv",
    },
    "wd-vit-large-tagger-v3": {
        "kind": "wd",
        "repo_id": "SmilingWolf/wd-vit-large-tagger-v3",
        "revision": "main",
        "model_path": "model.onnx",
        "tags_path": "selected_tags.csv",
    },
    "wd-vit-v3": {
        "kind": "wd",
        "repo_id": "SmilingWolf/wd-vit-tagger-v3",
        "revision": "main",
        "model_path": "model.onnx",
        "tags_path": "selected_tags.csv",
    },
    "wd-swinv2-v3": {
        "kind": "wd",
        "repo_id": "SmilingWolf/wd-swinv2-tagger-v3",
        "revision": "main",
        "model_path": "model.onnx",
        "tags_path": "selected_tags.csv",
    },
    "wd-convnext-v3": {
        "kind": "wd",
        "repo_id": "SmilingWolf/wd-convnext-tagger-v3",
        "revision": "main",
        "model_path": "model.onnx",
        "tags_path": "selected_tags.csv",
    },
    "wd14-convnextv2-v2": {
        "kind": "wd",
        "repo_id": "SmilingWolf/wd-v1-4-convnextv2-tagger-v2",
        "revision": "v2.0",
        "model_path": "model.onnx",
        "tags_path": "selected_tags.csv",
    },
    "wd14-moat-v2": {
        "kind": "wd",
        "repo_id": "SmilingWolf/wd-v1-4-moat-tagger-v2",
        "revision": "v2.0",
        "model_path": "model.onnx",
        "tags_path": "selected_tags.csv",
    },
    "wd14-vit-v2": {
        "kind": "wd",
        "repo_id": "SmilingWolf/wd-v1-4-vit-tagger-v2",
        "revision": "v2.0",
        "model_path": "model.onnx",
        "tags_path": "selected_tags.csv",
    },
    "wd14-convnext-v2": {
        "kind": "wd",
        "repo_id": "SmilingWolf/wd-v1-4-convnext-tagger-v2",
        "revision": "v2.0",
        "model_path": "model.onnx",
        "tags_path": "selected_tags.csv",
    },
    "wd14-swinv2-v2": {
        "kind": "wd",
        "repo_id": "SmilingWolf/wd-v1-4-swinv2-tagger-v2",
        "revision": "v2.0",
        "model_path": "model.onnx",
        "tags_path": "selected_tags.csv",
    },
    "wd14-convnextv2-v2-git": {
        "kind": "wd",
        "repo_id": "SmilingWolf/wd-v1-4-convnextv2-tagger-v2",
        "revision": "main",
        "model_path": "model.onnx",
        "tags_path": "selected_tags.csv",
    },
    "wd14-vit-v2-git": {
        "kind": "wd",
        "repo_id": "SmilingWolf/wd-v1-4-vit-tagger-v2",
        "revision": "main",
        "model_path": "model.onnx",
        "tags_path": "selected_tags.csv",
    },
    "wd14-convnext-v2-git": {
        "kind": "wd",
        "repo_id": "SmilingWolf/wd-v1-4-convnext-tagger-v2",
        "revision": "main",
        "model_path": "model.onnx",
        "tags_path": "selected_tags.csv",
    },
    "wd14-swinv2-v2-git": {
        "kind": "wd",
        "repo_id": "SmilingWolf/wd-v1-4-swinv2-tagger-v2",
        "revision": "main",
        "model_path": "model.onnx",
        "tags_path": "selected_tags.csv",
    },
    "wd14-vit": {
        "kind": "wd",
        "repo_id": "SmilingWolf/wd-v1-4-vit-tagger",
        "revision": "main",
        "model_path": "model.onnx",
        "tags_path": "selected_tags.csv",
    },
    "wd14-convnext": {
        "kind": "wd",
        "repo_id": "SmilingWolf/wd-v1-4-convnext-tagger",
        "revision": "main",
        "model_path": "model.onnx",
        "tags_path": "selected_tags.csv",
    },
}

DEFAULT_MODEL = "wd14-moat-v2"
